import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterModule } from '@angular/router';

import { TorgaPedidosSharedModule } from 'app/shared';
import {
    ProductosDormitorioComponent,
    ProductosDormitorioDetailComponent,
    ProductosDormitorioUpdateComponent,
    ProductosDormitorioCategoriaComponent,
    ProductosDormitorioChinfonierComponent,
    ProductosDormitorioDeletePopupComponent,
    ProductosModulosBajosComponent,
    ProductosVitrinasComponent,
    ProductosDormitorioCabecerosComponent,
    ProductosEscritoriosComponent,
    ArmariosDormitorioComponent,
    VestidoresDormitorioComponent,
    RinconDormitorioComponent,
    ArmariosDormitorioVistaComponent,
    ArmariosDormitorioOcultaComponent,
    ProductosDormitorioApoyoComponent,
    ProductosAparadoresComponent,
    ProductosMesasComponent,
    ProductosComodaComponent,
    ProductosPanelesComponent,
    ProductosSuplementosTvComponent,
    ProductosColgantesComponent,
    ProductosBuscadorComponent,
    ProductosBuscadorComponent2,
    ProductosBuscadorComponent3,
    ProductosSingularesComponent,
    ProductosAuxComponent,
    ProductosDormitorioDeleteDialogComponent,
    productosDormitorioRoute,
    productosDormitorioPopupRoute,
    ProductosEditarComponent
} from './';

const ENTITY_STATES = [...productosDormitorioRoute, ...productosDormitorioPopupRoute];

@NgModule({
    imports: [TorgaPedidosSharedModule, RouterModule.forChild(ENTITY_STATES)],
    declarations: [
        ProductosDormitorioComponent,
        ProductosDormitorioDetailComponent,
        ProductosDormitorioApoyoComponent,
        ProductosBuscadorComponent,
        ProductosComodaComponent,
        ProductosDormitorioCabecerosComponent,
        ProductosAparadoresComponent,
        ProductosMesasComponent,
        ProductosAuxComponent,
        ProductosVitrinasComponent,
        ProductosPanelesComponent,
        RinconDormitorioComponent,
        VestidoresDormitorioComponent,
        ArmariosDormitorioVistaComponent,
        ProductosSuplementosTvComponent,
        ProductosEscritoriosComponent,
        ProductosBuscadorComponent2,
        ProductosBuscadorComponent3,
        ArmariosDormitorioOcultaComponent,
        ProductosSingularesComponent,
        ProductosColgantesComponent,
        ProductosDormitorioChinfonierComponent,
        ProductosModulosBajosComponent,
        ArmariosDormitorioComponent,
        ProductosDormitorioCategoriaComponent,
        ProductosDormitorioUpdateComponent,
        ProductosDormitorioDeleteDialogComponent,
        ProductosDormitorioDeletePopupComponent,
        ProductosEditarComponent
    ],
    entryComponents: [
        ProductosDormitorioComponent,
        ProductosDormitorioApoyoComponent,
        ProductosComodaComponent,
        ProductosDormitorioCabecerosComponent,
        ProductosAparadoresComponent,
        ArmariosDormitorioComponent,
        ProductosEscritoriosComponent,
        ProductosAuxComponent,
        RinconDormitorioComponent,
        ProductosPanelesComponent,
        ProductosVitrinasComponent,
        VestidoresDormitorioComponent,
        ProductosSuplementosTvComponent,
        ArmariosDormitorioVistaComponent,
        ProductosBuscadorComponent2,
        ProductosBuscadorComponent3,
        ProductosMesasComponent,
        ProductosColgantesComponent,
        ArmariosDormitorioOcultaComponent,
        ProductosDormitorioCategoriaComponent,
        ProductosBuscadorComponent,
        ProductosDormitorioChinfonierComponent,
        ProductosDormitorioUpdateComponent,
        ProductosSingularesComponent,
        ProductosModulosBajosComponent,
        ProductosDormitorioDeleteDialogComponent,
        ProductosDormitorioDeletePopupComponent,
        ProductosEditarComponent
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class TorgaPedidosProductosDormitorioModule {}
